### ISSUE TITLE
Add SASS Support

### ISSUE THREAD

**Issue by ginnwork** [panique/php-sass#9]
The project - despite its name #5 - does not support parsing `.sass` files. However, the fix is fairly easy; all that needs to be changed is the `glob()` pattern. https://github.com/panique/php-sass/blob/e44d42da79e5a06cfa7d01011f72a194e62646e7/sass-compiler.php#L42

I unfortunately don't have time to write a PR right now. I hope my feedback helps resolve the issue.

**Comment by ginnwork** [comment]
That was not the fix unfortunately. https://github.com/leafo/scssphp does not support `.sass` syntax so this ticket is irrelevant.

**Comment by panique** [comment]
Hey, yes that's is actually true and a weird thing in the SASS / SCSS world (i was working in several teams over the years and everybody called scss just "sass" even if it's wrong).

I'm totally with you, but currently lots of people are using this lib in production, and i would like not to add breaking changes, there are also better tools for the job right now (this project is nearly 5 years old).
